apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: yellow
spec:
  encryptedData:
    a: AgCuNtvjFDfx5bWqNxHZEIDrgyGdbKe9HpnRyApvPqxNFWZqT1QYU1Y9JBQtnxYqhc6Y0vY54OFDB/1UThI40maKzjdeM8tw4opF4Pgogs3Nch4nPgPz2PGvSU/TpR4FyJM97PKctYwzNkXg25m9//U9GgRr1no1yRCyD2utKDQWl6zGCmHW0/XC3UDzo66aV6UvRu2gSUJe/QWVb+eyUybTTR9Uawvu0VEootOzR/rFRGRW5XyBxkHVa5gFPXlle2zOs7kpCzd1UciIYZZOIhPgOTTWeahNabvwKo9gTLHaEfHvHnooyCD+XRydGbbapndRalWWI/QdRWTXmtDVmYXr81Qq5qEi/rwHjHLt0FSL5dHy0VXgoqLrJlmS1KNue63bkLDiyLUm2ul/CzlF3Ekr6zvbiooND3uoJP0pb95ZxD94DSpO7Eaq7poNp69j8leF1b5ElqWV+ql74NntWvyLtoXgVhAPMlbVWxZILou8iICDtCIRA+WeQ54fYZDSgj82oubRzridfu+nOcK+3DnCJ17xSkmXD5nQXWxSBbGDj/Q+ehnI+UAlY9+0EjjgF1azw4PHQlfGPTSF4EA7cqi4Fk57yNfGnqNooAZX7CFHX//LNK4xLU2qpvIsXAR0OUG2xgJ2evz2kFPkFaomiUK/QOx0Xr5mF8PPnXUD3AfI8j3/Kd0t3rkP6kW3YhsWWw4p
    b: AgC1tOiPsWm2JIhEm7lukLJxsPwvu544Gg6jsy+jmBj5xF27UJFbhUMcf8ThspBR8/2jHd1vXHjLuRHB6lJlO8ihSnB2JQvI38FVyUccEd53zCXa/kRL0/R4+3I10ARDOgAMsCb3chdiz2zzE3UDC4GalqkPkPmXN8N2lwC45ZWgKyZ+0+MNkM4hDTAFAVYzGWeLpz18RD/ING3zO4eK7vIEZ/EvPmWyPXnUdro1Xcim8gXT/HP1aNjgeiQxqVAIcUdp2CzzOYq5Tyy3N+KjF6IwYScqgask/4unggFnBCCs71nmt1UUMoTg8+SkzU+ojZkjarDcEZYFBW4FqHbWVWRsv0EJqI5GZBtC+uDT3Y3LsIBgiYdPsl/2nGQ5iEvLEeJnJgxjc36o2SVyd3unjPoUQ8dQmIKNj/fc4R+Rpar6q0eMgXgiGS24FUjBnC6pyV2+l/tyVZvEblQtLpYO6FEbHyScuqQJF8ve4sCdZSafkPMa9QeChdkMRLKn0bGXArTFxcfxc7PZ4thWsZItz7BIWRxguE1SQ5mj29NjrlDGSQ2V0bRP/oVHTG03meiyLolLBsMLzfubwnxtFUJKrG05R7QH3EjrKPYEfen7IYvJJArsaYzwSKXYKUOlExNZ5azNs46mkEe2rA5J7d7Y+23NBuUt65zvYdYAYzxR5w6nc9NWXmB9gHVKHB+3g3HoJpjo
  template:
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: yellow